# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AirportLocator' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AirportLocator
  pod 'SwiftyJSON'
  pod 'Alamofire'

  target 'AirportLocatorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AirportLocatorUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
